version: '3'
services:
  python3:
    restart: always
    user: "${UID}:${GID}"
    build: .
    container_name: 'python392'
    ports: 
      - 8888:8888
    tty: true
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ${PWD}/opt:/home/ikoma/workspaces/
    working_dir: '/home/ikoma/workspaces/'