version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python392'
    ports: 
      - 8888:8888
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt